# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tobias/Cloud-Volumetric-Ray-Marching

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tobias/Cloud-Volumetric-Ray-Marching

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/Cloud-Volumetric-Ray-Marching/CMakeFiles /home/tobias/Cloud-Volumetric-Ray-Marching//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/Cloud-Volumetric-Ray-Marching/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named gloom

# Build rule for target.
gloom:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gloom
.PHONY : gloom

# fast build rule for target.
gloom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/build
.PHONY : gloom/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f gloom/vendor/glfw/src/CMakeFiles/glfw.dir/build.make gloom/vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

gloom/src/gloom/glfont.o: gloom/src/gloom/glfont.cpp.o

.PHONY : gloom/src/gloom/glfont.o

# target to build an object file
gloom/src/gloom/glfont.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glfont.cpp.o
.PHONY : gloom/src/gloom/glfont.cpp.o

gloom/src/gloom/glfont.i: gloom/src/gloom/glfont.cpp.i

.PHONY : gloom/src/gloom/glfont.i

# target to preprocess a source file
gloom/src/gloom/glfont.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glfont.cpp.i
.PHONY : gloom/src/gloom/glfont.cpp.i

gloom/src/gloom/glfont.s: gloom/src/gloom/glfont.cpp.s

.PHONY : gloom/src/gloom/glfont.s

# target to generate assembly for a file
gloom/src/gloom/glfont.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glfont.cpp.s
.PHONY : gloom/src/gloom/glfont.cpp.s

gloom/src/gloom/glutils.o: gloom/src/gloom/glutils.cpp.o

.PHONY : gloom/src/gloom/glutils.o

# target to build an object file
gloom/src/gloom/glutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glutils.cpp.o
.PHONY : gloom/src/gloom/glutils.cpp.o

gloom/src/gloom/glutils.i: gloom/src/gloom/glutils.cpp.i

.PHONY : gloom/src/gloom/glutils.i

# target to preprocess a source file
gloom/src/gloom/glutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glutils.cpp.i
.PHONY : gloom/src/gloom/glutils.cpp.i

gloom/src/gloom/glutils.s: gloom/src/gloom/glutils.cpp.s

.PHONY : gloom/src/gloom/glutils.s

# target to generate assembly for a file
gloom/src/gloom/glutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/glutils.cpp.s
.PHONY : gloom/src/gloom/glutils.cpp.s

gloom/src/gloom/imageLoader.o: gloom/src/gloom/imageLoader.cpp.o

.PHONY : gloom/src/gloom/imageLoader.o

# target to build an object file
gloom/src/gloom/imageLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/imageLoader.cpp.o
.PHONY : gloom/src/gloom/imageLoader.cpp.o

gloom/src/gloom/imageLoader.i: gloom/src/gloom/imageLoader.cpp.i

.PHONY : gloom/src/gloom/imageLoader.i

# target to preprocess a source file
gloom/src/gloom/imageLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/imageLoader.cpp.i
.PHONY : gloom/src/gloom/imageLoader.cpp.i

gloom/src/gloom/imageLoader.s: gloom/src/gloom/imageLoader.cpp.s

.PHONY : gloom/src/gloom/imageLoader.s

# target to generate assembly for a file
gloom/src/gloom/imageLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/imageLoader.cpp.s
.PHONY : gloom/src/gloom/imageLoader.cpp.s

gloom/src/gloom/lodepng.o: gloom/src/gloom/lodepng.cpp.o

.PHONY : gloom/src/gloom/lodepng.o

# target to build an object file
gloom/src/gloom/lodepng.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/lodepng.cpp.o
.PHONY : gloom/src/gloom/lodepng.cpp.o

gloom/src/gloom/lodepng.i: gloom/src/gloom/lodepng.cpp.i

.PHONY : gloom/src/gloom/lodepng.i

# target to preprocess a source file
gloom/src/gloom/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/lodepng.cpp.i
.PHONY : gloom/src/gloom/lodepng.cpp.i

gloom/src/gloom/lodepng.s: gloom/src/gloom/lodepng.cpp.s

.PHONY : gloom/src/gloom/lodepng.s

# target to generate assembly for a file
gloom/src/gloom/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/lodepng.cpp.s
.PHONY : gloom/src/gloom/lodepng.cpp.s

gloom/src/gloom/shapes.o: gloom/src/gloom/shapes.cpp.o

.PHONY : gloom/src/gloom/shapes.o

# target to build an object file
gloom/src/gloom/shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/shapes.cpp.o
.PHONY : gloom/src/gloom/shapes.cpp.o

gloom/src/gloom/shapes.i: gloom/src/gloom/shapes.cpp.i

.PHONY : gloom/src/gloom/shapes.i

# target to preprocess a source file
gloom/src/gloom/shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/shapes.cpp.i
.PHONY : gloom/src/gloom/shapes.cpp.i

gloom/src/gloom/shapes.s: gloom/src/gloom/shapes.cpp.s

.PHONY : gloom/src/gloom/shapes.s

# target to generate assembly for a file
gloom/src/gloom/shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/shapes.cpp.s
.PHONY : gloom/src/gloom/shapes.cpp.s

gloom/src/gloom/timeutils.o: gloom/src/gloom/timeutils.cpp.o

.PHONY : gloom/src/gloom/timeutils.o

# target to build an object file
gloom/src/gloom/timeutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/timeutils.cpp.o
.PHONY : gloom/src/gloom/timeutils.cpp.o

gloom/src/gloom/timeutils.i: gloom/src/gloom/timeutils.cpp.i

.PHONY : gloom/src/gloom/timeutils.i

# target to preprocess a source file
gloom/src/gloom/timeutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/timeutils.cpp.i
.PHONY : gloom/src/gloom/timeutils.cpp.i

gloom/src/gloom/timeutils.s: gloom/src/gloom/timeutils.cpp.s

.PHONY : gloom/src/gloom/timeutils.s

# target to generate assembly for a file
gloom/src/gloom/timeutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/gloom/timeutils.cpp.s
.PHONY : gloom/src/gloom/timeutils.cpp.s

gloom/src/logic.o: gloom/src/logic.cpp.o

.PHONY : gloom/src/logic.o

# target to build an object file
gloom/src/logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/logic.cpp.o
.PHONY : gloom/src/logic.cpp.o

gloom/src/logic.i: gloom/src/logic.cpp.i

.PHONY : gloom/src/logic.i

# target to preprocess a source file
gloom/src/logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/logic.cpp.i
.PHONY : gloom/src/logic.cpp.i

gloom/src/logic.s: gloom/src/logic.cpp.s

.PHONY : gloom/src/logic.s

# target to generate assembly for a file
gloom/src/logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/logic.cpp.s
.PHONY : gloom/src/logic.cpp.s

gloom/src/main.o: gloom/src/main.cpp.o

.PHONY : gloom/src/main.o

# target to build an object file
gloom/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/main.cpp.o
.PHONY : gloom/src/main.cpp.o

gloom/src/main.i: gloom/src/main.cpp.i

.PHONY : gloom/src/main.i

# target to preprocess a source file
gloom/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/main.cpp.i
.PHONY : gloom/src/main.cpp.i

gloom/src/main.s: gloom/src/main.cpp.s

.PHONY : gloom/src/main.s

# target to generate assembly for a file
gloom/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/main.cpp.s
.PHONY : gloom/src/main.cpp.s

gloom/src/program.o: gloom/src/program.cpp.o

.PHONY : gloom/src/program.o

# target to build an object file
gloom/src/program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/program.cpp.o
.PHONY : gloom/src/program.cpp.o

gloom/src/program.i: gloom/src/program.cpp.i

.PHONY : gloom/src/program.i

# target to preprocess a source file
gloom/src/program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/program.cpp.i
.PHONY : gloom/src/program.cpp.i

gloom/src/program.s: gloom/src/program.cpp.s

.PHONY : gloom/src/program.s

# target to generate assembly for a file
gloom/src/program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/program.cpp.s
.PHONY : gloom/src/program.cpp.s

gloom/src/sceneGraph.o: gloom/src/sceneGraph.cpp.o

.PHONY : gloom/src/sceneGraph.o

# target to build an object file
gloom/src/sceneGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/sceneGraph.cpp.o
.PHONY : gloom/src/sceneGraph.cpp.o

gloom/src/sceneGraph.i: gloom/src/sceneGraph.cpp.i

.PHONY : gloom/src/sceneGraph.i

# target to preprocess a source file
gloom/src/sceneGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/sceneGraph.cpp.i
.PHONY : gloom/src/sceneGraph.cpp.i

gloom/src/sceneGraph.s: gloom/src/sceneGraph.cpp.s

.PHONY : gloom/src/sceneGraph.s

# target to generate assembly for a file
gloom/src/sceneGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/src/sceneGraph.cpp.s
.PHONY : gloom/src/sceneGraph.cpp.s

gloom/vendor/glad/src/glad.o: gloom/vendor/glad/src/glad.c.o

.PHONY : gloom/vendor/glad/src/glad.o

# target to build an object file
gloom/vendor/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/vendor/glad/src/glad.c.o
.PHONY : gloom/vendor/glad/src/glad.c.o

gloom/vendor/glad/src/glad.i: gloom/vendor/glad/src/glad.c.i

.PHONY : gloom/vendor/glad/src/glad.i

# target to preprocess a source file
gloom/vendor/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/vendor/glad/src/glad.c.i
.PHONY : gloom/vendor/glad/src/glad.c.i

gloom/vendor/glad/src/glad.s: gloom/vendor/glad/src/glad.c.s

.PHONY : gloom/vendor/glad/src/glad.s

# target to generate assembly for a file
gloom/vendor/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gloom.dir/build.make CMakeFiles/gloom.dir/gloom/vendor/glad/src/glad.c.s
.PHONY : gloom/vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glfw"
	@echo "... gloom"
	@echo "... gloom/src/gloom/glfont.o"
	@echo "... gloom/src/gloom/glfont.i"
	@echo "... gloom/src/gloom/glfont.s"
	@echo "... gloom/src/gloom/glutils.o"
	@echo "... gloom/src/gloom/glutils.i"
	@echo "... gloom/src/gloom/glutils.s"
	@echo "... gloom/src/gloom/imageLoader.o"
	@echo "... gloom/src/gloom/imageLoader.i"
	@echo "... gloom/src/gloom/imageLoader.s"
	@echo "... gloom/src/gloom/lodepng.o"
	@echo "... gloom/src/gloom/lodepng.i"
	@echo "... gloom/src/gloom/lodepng.s"
	@echo "... gloom/src/gloom/shapes.o"
	@echo "... gloom/src/gloom/shapes.i"
	@echo "... gloom/src/gloom/shapes.s"
	@echo "... gloom/src/gloom/timeutils.o"
	@echo "... gloom/src/gloom/timeutils.i"
	@echo "... gloom/src/gloom/timeutils.s"
	@echo "... gloom/src/logic.o"
	@echo "... gloom/src/logic.i"
	@echo "... gloom/src/logic.s"
	@echo "... gloom/src/main.o"
	@echo "... gloom/src/main.i"
	@echo "... gloom/src/main.s"
	@echo "... gloom/src/program.o"
	@echo "... gloom/src/program.i"
	@echo "... gloom/src/program.s"
	@echo "... gloom/src/sceneGraph.o"
	@echo "... gloom/src/sceneGraph.i"
	@echo "... gloom/src/sceneGraph.s"
	@echo "... gloom/vendor/glad/src/glad.o"
	@echo "... gloom/vendor/glad/src/glad.i"
	@echo "... gloom/vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

